version: "3"

services:

  php-fpm:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: ${PROJECT_NAME}-phpfpm
    working_dir: /application
    volumes:
      - ./src:/application
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini
    networks:
      - network-app

  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    working_dir: /application
    volumes:
      - ./src:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8383:80
    networks:
      - network-app

  postgres:
    image: postgres:alpine
    container_name: ${PROJECT_NAME}-postgres
    ports:
      - 5433:5432
    working_dir: /application
    volumes:
      - ./.db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - network-app

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    ports:
      - 6379:6379
    networks:
      - network-app

  mailpit:
    image: axllent/mailpit
    container_name: ${PROJECT_NAME}-mailpit
    volumes:
      - ./.mail_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - network-app

volumes:
  db_data:

networks:
  network-app:
